require 'socket'
require 'fileutils'
require 'yaml'
require 'pp'
require 'tempfile'
require 'benchmark'
require 'thread'
require 'time'
begin
  require 'thor'
  require 'thor/group'
  require 'multi_json'
  require 'fog'
  require 'colored'
  require 'highline/import'
  require 'spinning_cursor'
rescue LoadError
  require 'rubygems'
  require 'thor'
  require 'thor/group'
  require 'multi_json'
  require 'fog'
  require 'colored'
  require 'highline/import'
  require 'spinning_cursor'
end

module Ankus
  require 'ankus/settings'
  require 'ankus/version'
  require 'ankus/helper'
  require 'ankus/config_parser'
  require 'ankus/cli'
  require 'ankus/inventory'
  require 'ankus/utils'
  require 'ankus/cloud_init'
  require 'ankus/cloud_manage'
  require 'ankus/deploy'
  require 'ankus/errors'
  require 'ankus/logging'
end
