require 'socket'
require 'fileutils'
require 'yaml'
require 'pp'
require 'tempfile'
require 'benchmark'
require 'thread'
begin
  require 'thor'
  require 'thor/group'
  require 'multi_json'
  require 'fog'
  require 'colored'
  require 'highline/import'
rescue LoadError
  require 'rubygems'
  require 'thor'
  require 'thor/group'
  require 'multi_json'
  require 'fog'
  require 'colored'
  require 'highline/import'
end

module Ankuscli
  require 'ankuscli/version'
  require 'ankuscli/helper'
  require 'ankuscli/config_parser'
  require 'ankuscli/cli'
  require 'ankuscli/inventory'
  require 'ankuscli/utils'
  require 'ankuscli/cloud_init'
  require 'ankuscli/cloud_manage'
  require 'ankuscli/deploy'
end